### ISSUE TITLE
make-figures.py does not work in osx

### ISSUE THREAD

**Issue by mgiustina** [DanielSank/theory#10]
** (inkscape-bin:4312): WARNING **: Can't open file: mutualInductance.svg (doesn't exist)

**Comment by DanielSank** [comment]
Are you in the right directory? How are you invoking the script?

**Comment by mgiustina** [comment]
This is a known osx issue with inkscape. I fixed it locally, will gladly
submit fix as PR.

**Comment by DanielSank** [comment]
OSX? But... why? ;-)

**Comment by mgiustina** [comment]
Because my work laptop is a mac and I'm not allowed to change its os.

**Comment by MostafaKhezri** [comment]
According to my experience, OSX is very weird with the command line. Never assume any script that is written in linux is going to work on OSX.

**Comment by DanielSank** [comment]
It's the talking Josephson junction!
