### ISSUE TITLE
Problem with Tex folder

### ISSUE THREAD

**Issue by MostafaKhezri** [DanielSank/theory#2]
Your Tex folder seems to have issue in github. Also when cloning, this directory is cloned, but it's empty.

**Comment by DanielSank** [comment]
Ah yes, it's a git submodule. Cloning repositories which use submodules requires slightly extra work or configuration. Should add to readme.

**Comment by DanielSank** [comment]
@MostafaKhezri how's that: 779f912062363c125d2610517c2d3f7ac84264ff

**Comment by MostafaKhezri** [comment]
It's good now :)

**Comment by DanielSank** [comment]
https://github.com/DanielSank/theory/commit/df35e9dc263e6a4fbecdd7d8882948de589ce789
