### ISSUE TITLE
Spelling typos 

### ISSUE THREAD

**Issue by MaxParadiz** [DanielSank/theory#33]
driving.tex, 15
"If $C_d$ is sufficiently small, it's impedance..."
it's > its

driving.tex 31& 118, coupling.tex 109, parallel_LC.tex 10
Kirchoff > Kirchhoff

rotating_frame.tex, 4
"the qubit state processes about an axis in the Block sphere"
processes > precesses

decoherence.tex 38
"we can shoose it to be"
shoose > choose

decoherence.tex 59
"drive line is can be computed"
extra 'is'

**Comment by DanielSank** [comment]
Thank you, Max. I'd like to know: how did you find this repository?

**Comment by MaxParadiz** [comment]
No problem! Thank you for writing this very interesting document (I am still not ready to understand it in its entirety, but might come back in a few weeks!) 

I saw your post in the Quantum Computing sub-reddit :)
