### ISSUE TITLE
Suggestions, typos, and notational inconsistencies in qubits 101

### ISSUE THREAD

**Issue by amopremcak** [DanielSank/theory#48]
1. In footnote 3 of section 3.1, there are missing spaces between 50 and \Omega in the first and last sentences. The last sentence is missing a period at the end.

2. In footnote 4 of section 3.1, an additional quality factor Q_l is introduced. It might be better to stick with Q_d as this is defined in the text.

3. The symmetry between sections 3.1 and 3.3 could be improved by adding a subscript d to the symbol for the mutual. This would change a large number of equations as well as figure 2. I mention this because the table in section 7.1 uses the notation M_d, but section 3.3 uses M.

4. Equation (33) has a \dot{\Phi_2}} instead of a \dot{\Phi}_2 in the coupling term.

5. The symmetry between sections 4.1 and 4.3 could be improved if a \bold{C} was used in place of T_C to denote the capacitance matrix.

6. In section 4.3, there is a period missing at the end of equation (44).

7. Equation (61) is missing a ^\dagger on the rightmost R of the first line. 

8. In the table of section 5.2, the symbols C_q and L_q are used in reference to sections 3.1 and 3.3. Consistency could be improved by using the same symbols to label the capacitor and inductor of the qubit in figures 1 and 2. Additionally, the symbol M_d is used here which relates back to the suggestion given in item number 3.

9. There are a lot of \omega's introduced in section 5. You do a nice job of defining each of them, but I feel like there could be a way to eliminate one or two of them. Also, the symbol \delta \omega is defined once in the introduction to be \omega_q = \omega_0 + \delta \omega, and then later in section 5.2 to be \delta \omega \equiv \omega_d - \omega_r.

10. The table in section 5.3 uses \omega_1 and \omega_2 to denote the qubit frequencies, but a few sentences below the symbols \omega_{r_1} and \omega_{r_2} to denote the same thing.

11. Are the ground symbols in Fig. 5 intentionally lacking?

12. In section 7.2, the equations for the unitary U(t) uses both t and \delta t.

13. In section 7.4, is there a reason to use -\frac{\Omega}{2} over -\frac{\omega_q}{2}? Also, the formulas for the transition rates uses \omega_q instead of \Omega.

**Comment by amopremcak** [comment]
14. The flux transition rate formula uses symbol M instead of M_d in accordance with section 7.

**Comment by DanielSank** [comment]
I've moved those items from the list that are not trivial to fix to their own issues.
