### ISSUE TITLE
Confusing definitions of omega in rotating coupling section

### ISSUE THREAD

**Issue by DanielSank** [DanielSank/theory#52]
From @amopremcak:

The table in section 5.3 uses \omega_1 and \omega_2 to denote the qubit frequencies, but a few sentences below the symbols \omega_{r_1} and \omega_{r_2} to denote the same thing.

**Comment by DanielSank** [comment]
In principle, the frame rotation frequencies do not have to be equal to the qubits' resonance frequencies. So \omega_1 and \omega_{r1} are not necessarily the same thing. Could you recommend a way to clarify this point? @aopremcak

**Comment by amopremcak** [comment]
I see. I thought for some reason you were creating another variable for the qubit frequency. What you have now is totally fine, and \omega_{r1} and \omega_{r2} make sense with respect to the notation used at the start of section 5.
