### ISSUE TITLE
Missing Minus Signs in Qubits 101

### ISSUE THREAD

**Issue by amopremcak** [DanielSank/theory#63]
In the table of section 5.3, I believe the expression for 2g/\hbar \sqrt{\omega_1 \omega_2} is missing a minus sign for the inductive case.

In section 7.2, the first equation for H_d is missing a minus sign in front of the sign if the earlier findings refer to equation (38). Also, the inline expression for f(t) above this equation might be missing a subscript on the \omega.

**Comment by DanielSank** [comment]
The table in 5.2 was missing a minus as well.
