### ISSUE TITLE
parallelSeriesEquivalence.tex references nonexistent graphic parallelSeriesEquivalent.pdf

### ISSUE THREAD

**Issue by mgiustina** [DanielSank/theory#8]
In line 25.

Presumably the python figure maker should take care of this. When I try to build `circuits` with `$ pdflatex circuits.tex`, the figure is never created.

**Comment by DanielSank** [comment]
Yeah, I haven't gone through and added a figure-maker script for every document. In the meanwhile, to do it yourself, load the svg in Inkscape and then just save-as pdf.

**Comment by mgiustina** [comment]
`$ python make-figures.py
sh: line 4: inkscape: command not found`

**Comment by DanielSank** [comment]
Yep, install inkscape. Or use your favorite svg->pdf tool.

**Comment by DanielSank** [comment]
Oh, hah, the python script is already there. Ok in that case this issue is a "wontfix" because the problem is that you have to install inkscape. Maybe I should put that in big letters in the README...

**Comment by DanielSank** [comment]
Sorry, I shouldn't have closed this so fast. Is the issue resolved to your satisfaction?

**Comment by mgiustina** [comment]
You might want to update the readme to mention that not only tex but also python and inkscape are needed.

**Comment by DanielSank** [comment]
Added an issue about that.

**Comment by DanielSank** [comment]
Based on comment in #9, closing.
